language: php
php:
  - "5.3"
  - "5.4"

before_install:
 - cd ..
 - git clone git://github.com/zendframework/ZendSkeletonApplication.git
 - cd ZendSkeletonApplication
 - cp ../WalyDevcloudHook/.travis/composer.json ./
 - curl -s http://getcomposer.org/installer | php
 - php composer.phar install --dev
 - rm -rf vendor/iwalz/walydevcloudhook
 - cp -r ../WalyDevcloudHook vendor/iwalz/walydevcloudhook
 - cd vendor/iwalz/walydevcloudhook
 - ls -la ../

script:
 - cd tests/
 - phpunit
